pnml_type: pnml
model_degree: 3
lamb: 0
x_test_max: 1.0
x_test_min: 0
dx_test: 0.01
is_multi_process: true
y_max: 100
y_min: 1e-20 # Constructing the interval such that: [-y_max:y_min]+[0]+[y_min:y_max]
y_num: 50000
min_sigma_square: 1e-3
x_train: [0.055, 0.655, 0.855, 0.995]
y_train: [-0.1, 0.5, 0.2, 0.1]
data_type: fourier # polynomial
is_adaptive: false

hydra:
  run:
    # Output directory
    dir: ../output/pnml_fourier_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ../output/
    subdir: pnml_fourier_${now:%Y%m%d_%H%M%S}_${hydra.job.num}