pnml_type: pnml_min_norm
model_degree: 4
x_test_max: 1.0
x_test_min: 0
dx_test: 0.01
x_train: [0.055, 0.105, 0.635, 0.655, 0.955, 0.965]
y_train: [-0.1,0, 0.6, 0.55, 0.2, 0.1]
data_type: fourier
sigma_square: 1e-3

lamb: 0
constrain_factor: 1.0

# Machine params
is_local_mode: false  # Whether to use ray debug mode: using only 1 cpu.
num_cpus: -1          # Number of cpu to use. Set -1 to use all available cpus.

# Optimization params
pnml_lambda_optim_dict:
  tol_func: 1e-6
  tol_lamb: 1e-16
  max_iter: 1e4

hydra:
  run:
    # Output directory
    dir: ../output/pnml_min_norm_fourier_${now:%Y%m%d_%H%m%S}
  sweep:
    dir: ../output/
    subdir: pnml_fourier_${now:%Y%m%d_%H%m%S}_${hydra.job.num}