data_dir: ../data               # directory to store the downloaded data in
n_trails: 3                     # Number of repetition per experiment. Each with different random initialization
num_trainset_sizes: 30          # Number of trainset sizes to eval
trainset_sizes: []
seed: -1
fast_dev_run: false

# Preprocess param
is_standardize_feature: true
is_standardize_samples: false
is_add_bias_term: true

# Learner params
is_eval_mdl: true
is_eval_empirical_pnml: true
is_eval_analytical_pnml: true

pnml_params_dict: {
    var_type: "genie_valset" # genie_valset/genie_valset_no_train/adaptive_var/mn_var
}

# Machine params
is_local_mode: false            # Whether to use ray debug mode: using only 1 cpu.
num_cpus: -1                    # Number of cpu to use. Set -1 to use all available cpus.
is_datasets_statistics: false   # Whether to download all regression datasets.

# Datasets to analyze
dataset_names:
  - "645_fri_c3_500_50"

hydra:
  run:
    # Output directory
    dir: ../output/real_data_${now:%Y%m%d_%H%m%S}
  sweep:
    dir: ../output/
    subdir: real_data_${now:%Y%m%d_%H%m%S}_${hydra.job.num}