data_dir: ../data/UCI_Datasets  # directory to store the downloaded data in
n_trails: 1                     # Number of repetition per experiment. Each with different random initialization
trainset_sizes: []              # Number of trainset sizes to eval. if empty use default
fast_dev_run: false

# Preprocess param
is_standardize_features: true
is_add_bias_term: true

# Machine params
is_local_mode: false            # Whether to use ray debug mode: using only 1 cpu.
num_cpus: -1                    # Number of cpu to use. Set -1 to use all available cpus.

# Datasets to analyze
dataset_name: bostonHousing
# concrete
# energy
# kin8nm
# naval-propulsion-plant # todo: this producing a lot of prints
# power-plant
# protein-tertiary-structure
# wine-quality-red
# yacht


optimization_dict:
  pnml_lambda_optim_dict:
    tol_func: 1e-6
    tol_lamb: 1e-12
    max_iter: 1e4


train_test_split_num: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17 ,18 ,19]

hydra:
  run:
    # Output directory
    dir: ../output/uci_experiment_${now:%Y%m%d_%H%m%S}
  sweep:
    dir: ../output/
    subdir: uci_experiment_${now:%Y%m%d_%H%m%S}_${hydra.job.num}